import scrapy

class CapecMitreViewItems(scrapy.Item):
    Capec_Type = scrapy.Field()
    View_Structure = scrapy.Field()
    View_Objective = scrapy.Field()
    Capec_ID = scrapy.Field()
    Capec_Name = scrapy.Field()
    Capec_status = scrapy.Field()
    View_Filter = scrapy.Field()
    View_Audience = scrapy.Field()
    Relationships = scrapy.Field()
    Relationship_Notes = scrapy.Field()
    Maintenance_Notes = scrapy.Field()
    Other_Notes = scrapy.Field()
    Alternate_Terms = scrapy.Field()
    Research_Gaps = scrapy.Field()
    References = scrapy.Field()
    Content_History = scrapy.Field()
    callback = scrapy.Field()


class CapecMitreCategoryItems(scrapy.Item):

    Capec_Type = scrapy.Field()
    Capec_ID = scrapy.Field()
    Capec_Name = scrapy.Field()
    Capec_status = scrapy.Field()
    Description = scrapy.Field()
    Related_Weakness = scrapy.Field()
    Attack_Prerequisite = scrapy.Field()
    Methods_of_Attack = scrapy.Field()
    Attacker_Skills_or_Knowledge_Required = scrapy.Field()
    Resources_Required = scrapy.Field()
    Attack_Motivation_Consequences = scrapy.Field()
    Relationships = scrapy.Field()
    Relationship_Notes = scrapy.Field()
    Maintenance_Notes = scrapy.Field()
    Background_Details = scrapy.Field()
    Other_Notes = scrapy.Field()
    Alternate_Terms = scrapy.Field()
    Research_Gaps = scrapy.Field()
    References = scrapy.Field()
    Content_History = scrapy.Field()
    callback = scrapy.Field()

class CapecMitreAttackPatternItems(scrapy.Item):
    Capec_Type = scrapy.Field()
    Capec_ID = scrapy.Field()
    Capec_Name = scrapy.Field()
    Capec_status = scrapy.Field()
    Capec_Pattern_Abstraction = scrapy.Field()
    Capec_Pattern_Completeness = scrapy.Field()
    Description = scrapy.Field()
    Alternate_Terms = scrapy.Field()
    Target_Attack_Surface = scrapy.Field()
    Attack_Prerequisites = scrapy.Field()
    Typical_Severity = scrapy.Field()
    Typical_Likelihood_of_Exploit = scrapy.Field()
    Methods_of_Attack = scrapy.Field()
    Examples_Instances = scrapy.Field()
    Attacker_Skills_or_Knowledge_Required = scrapy.Field()
    Resources_Required = scrapy.Field()
    Probing_Techniques = scrapy.Field()
    Indicators_Warnings_of_Attack = scrapy.Field()
    Obfuscation_Techniques = scrapy.Field()
    Solutions_and_Mitigations = scrapy.Field()
    Attack_Motivation_Consequences = scrapy.Field()
    Injection_Vector = scrapy.Field()
    Payload = scrapy.Field()
    Activation_Zone = scrapy.Field()
    Payload_Activation_Impact = scrapy.Field()
    Related_Weakness = scrapy.Field()
    Related_Vulnerabilities = scrapy.Field()
    Related_Attack_Patterns = scrapy.Field()
    Relevant_Security_Requirements = scrapy.Field()
    Relevant_Design_Patterns = scrapy.Field()
    Relevant_Security_Patterns = scrapy.Field()
    Related_Security_Principles = scrapy.Field()
    Related_Guidelines = scrapy.Field()
    Purposes = scrapy.Field()
    CIA_Impact = scrapy.Field()
    Technical_Context = scrapy.Field()
    Keywords = scrapy.Field()
    References = scrapy.Field()
    Other_Notes = scrapy.Field()
    Maintenance_Notes = scrapy.Field()
    Content_History = scrapy.Field()
    callback = scrapy.Field()

class CapecMitreEnvironmentItems(scrapy.Item):
    Capec_Type = scrapy.Field()
    Environment_ID = scrapy.Field()
    Environment_Title = scrapy.Field()
    Environment_Description = scrapy.Field()
    callback = scrapy.Field()

class CapecMitreCompoundElementsItems(scrapy.Item):
    Capec_Type = scrapy.Field()
    ID = scrapy.Field()
    Name = scrapy.Field()
    Compound_Element_Abstraction = scrapy.Field()
    Compound_Element_Completeness = scrapy.Field()
    Compound_Element_Structure = scrapy.Field()
    Status = scrapy.Field()
    Description = scrapy.Field()
    Relationships = scrapy.Field()
    Relationship_Notes = scrapy.Field()
    Maintenance_Notes = scrapy.Field()
    Background_Details = scrapy.Field()
    Other_Notes = scrapy.Field()
    Alternate_Terms = scrapy.Field()
    Research_Gaps = scrapy.Field()
    References = scrapy.Field()
    Content_History = scrapy.Field()
    callback = scrapy.Field()

class CapecMitreCommonAttackStepsItems(scrapy.Item):
    Capec_Type = scrapy.Field()
    Custom_Attack_StepType = scrapy.Field()
    Common_Attack_Step_ID = scrapy.Field()
    callback = scrapy.Field()

class CapecMitreCommonAttackSurfacesItems(scrapy.Item):
    Capec_Type = scrapy.Field()
    Target_Attack_Surface_DescriptionType = scrapy.Field()
    Common_Attack_Surface_ID = scrapy.Field()
    callback = scrapy.Field()
